In [ ]:
# Numpy Basics 

In [1]:
import numpy as np

In [3]:
#  1. Printing Statement 

print("Hello")

Hello


In [4]:
#  2. Printing values in variable 

a = 1
print(a)

b = 7.6
print(b)

c = "Hello"
print(c)

1
7.6
Hello


In [5]:
# one dimension array 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
# more than one dimension array 
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
# more than one dimension array 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
 3. Ndarray Object
      #  Parameters of ndarray Object
      #  numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

In [8]:
# minimum dimension - ndmin

a = np.array([1,2,3],ndmin = 0)
print(a)
print()
b = np.array([1,2,3],ndmin = 1)
print(b)
print()
c = np.array([1,2,3],ndmin = 2)
print(c)
print()
d = np.array([1,2,3],ndmin = 5)
print(d)

[1 2 3]

[1 2 3]

[[1 2 3]]

[[[[[1 2 3]]]]]


In [9]:
# Datatype Parameter - dtype 

a = np.array([1,2,3],dtype = int)
print(a)
print()
b = np.array([1,2,3],dtype = float)
print(b)
print()
c = np.array([1,2,3],dtype = complex)
print(c)

[1 2 3]

[1. 2. 3.]

[1.+0.j 2.+0.j 3.+0.j]


In [10]:
# 4. Data Type Objects (dtype)

a = np.dtype(np.int32)
print(a)
b = np.dtype(np.int64)
print(b)
print()
c = np.dtype('<i4')
print(c)

int32
int64

int32


In [10]:
# First Create a structured datatype
a = np.dtype([('age',np.int32)])
print(a)

[('age', '<i4')]


In [11]:
# Now apply it to ndarray object 

a = np.dtype([('age',np.int32)])
b = np.array([45,56,22,68,99],dtype = 'a')
print(b)

[b'45' b'56' b'22' b'68' b'99']


In [12]:
# One more example - creating a structured object and applying it to ndarray

a = np.dtype([('weight',np.float64)])
b = np.array([56.86,64.923,41.9632,27.05],dtype = 'a')
print(b)

[b'56.86' b'64.923' b'41.9632' b'27.05']


In [13]:
# One more example using string- creating a structured object and applying it to ndarray

a = np.dtype([('name','S20')])
b = np.array(['James','marks'],dtype = 'a')
print(b)

[b'James' b'marks']


In [14]:
# Using multiple fields

a = np.dtype([('name','S20'),('age','int32'),('roll_no','int64')])
b = np.array([('John','18','11234'),('Krish','22','112345'),('Anu','45','112674')],dtype = a)
print(b)

[(b'John', 18,  11234) (b'Krish', 22, 112345) (b'Anu', 45, 112674)]


In [ ]:
# 5. NumPy - Array Attributes

In [16]:
# simple array - One Dimensional Array and Two Dimensional Array
a = np.array([1,2,3])
print(a)
print()
b = np.array([[1,2,3],[4,5,6]])
print(b)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [17]:
# ndarray.shape
a = np.array([[1,2,3],[9,8,7]])
print(a.shape)

(2, 3)


In [20]:
# resizing the ndarray
a = np.array([[1,2,3],[9,8,7]])
a.shape = (3,2)
print(a)
print()
b = np.array([[1,2,3],[9,8,7]])
b.shape = (6,1)
print(b)

[[1 2]
 [3 9]
 [8 7]]

[[1]
 [2]
 [3]
 [9]
 [8]
 [7]]


In [26]:
# resizing the ndarray using reshape function
a = np.array([[1,2,3],[4,5,6]])
print(a)
print()
b = a.reshape(3,2)                       # 2rows 3columns resize to 3rows 2column
print(b)
print()
c = a.reshape(6,1)
print(c)                                # 2rows 3 columns resize into 6rows 1column

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [25]:
a = np.array([[1,2,3,7],[4,5,6,9]])
print(a)
print()
b = a.reshape(2,2,2)    # separates into 2 matrix (will have 3 [[[]]]  ).  Creating three dimensional array
print(b)

[[1 2 3 7]
 [4 5 6 9]]

[[[1 2]
  [3 7]]

 [[4 5]
  [6 9]]]


In [27]:
# One Dimensional Array using .arange

a = np.arange(10)
a.ndim               # optional
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
# Splitting the above program into two dimensional array

a = np.arange(9)
a.shape=(3,3)
print(a)

# Splitting the above program into three dimensional array
print()
b = np.arange(8)
b.shape=(2,2,2)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [40]:
# numpy.itemsize - (returns the length of each element of array in bytes).
a = np.array([1,2,3],'int32')
print(a.itemsize)
print()
b = np.array([1,2,3],'int64')
print(b.itemsize)
print()
c = np.array([1,2,3,4,5,6,8],'float32')
print(c.itemsize)
print()
d = np.array([1,2,3],'float32')
print(d.itemsize)
print()
a = np.array([1,2,3], dtype = 'int64')
print(a.itemsize)

4

8

4

4

8


In [41]:
# numpy.flags
# current values of all attributes in the object are returned
a = np.array([1,2,3,4])
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [44]:
# numpy.empty - (creates an uninitialized array of specified shape and dtype)

a = np.empty([2,3])
print(a)                  #values are randomly assigned with default datatype is float
print()
b = np.empty([3,3],dtype = 'int')
print(b)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
# numpy.zeros  -  Returns a new array of specified size, filled with zeros
a = np.zeros([3,3])
print(a)

# numpy.ones  -  Returns a new array of specified size, filled with ones
print()
b = np.ones([2,2])
print(b)
print()
c = np.ones([2,3],dtype='int')
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]]

[[1 1 1]
 [1 1 1]]


In [51]:
# numpy.asarray - converting list to ndarray

a = [1,2,3,4,5]
b = np.asarray(a)
print(b)
print()
a1 = ['a','b','c']
b1 = np.asarray(a1)
print(b1)
print()
a2 = [1,2,3,4,5]
b2 = np.asarray(a2, dtype = 'float')
print(b2)

[1 2 3 4 5]

['a' 'b' 'c']

[1. 2. 3. 4. 5.]


In [52]:
# numpy.asarray - converting tuple to ndarray

a = (1,2,3,4,5)
b = np.asarray(a)
print(b)
print()
a1 = ('a','b','c')
b1 = np.asarray(a1)
print(b1)
print()
a2 = (1,2,3),(4,5,6)
b2 = np.asarray(a2, dtype = 'float')
print(b2)

[1 2 3 4 5]

['a' 'b' 'c']

[[1. 2. 3.]
 [4. 5. 6.]]


In [53]:
# NumPy - Array From Numerical Ranges 

x = np.arange(10)
print(x)
print()
y = np.arange(10, dtype = 'float')
print(y)

[0 1 2 3 4 5 6 7 8 9]

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [55]:
# With start and stop parameters

a = np.arange(2,13)
print(a)

# With start and stop parameters along with increment
print()
b = np.arange(2,13,2)
print(b)

[ 2  3  4  5  6  7  8  9 10 11 12]

[ 2  4  6  8 10 12]


In [11]:
# numpy.linspace (instead of increment we use linespace)

x=np.linspace(0,20,5)
print (x)

[ 0.  5. 10. 15. 20.]


In [14]:
# endpoint set to false will not follow the increment step

x=np.linspace(0,20,5, endpoint = False)
print (x)

[ 0.  4.  8. 12. 16.]


In [15]:
# Finding steps b/w the consecutive numbers using retstep

x=np.linspace(0,20,5, retstep=True)
print (x)

(array([ 0.,  5., 10., 15., 20.]), 5.0)


In [16]:
# numpy.logspace

a = np.logspace(1,10,num=10,base = 2)   # 10 base 2 = 2 , so o/p (1*2^1 , 1*2^2 , 1*2^3, 1*2^4,....)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [17]:
a = np.logspace(1,10,num=10)     # here base is considered as 10 by default
print(a)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [19]:
# Numpy Indexing and Slicing 
# Slice Function

a=np.arange(10)
b=slice(2,8)
print(a[b])


# another methodd
print()
c=np.arange(10)
d=a[2:8]
print(d)

[2 3 4 5 6 7]

[2 3 4 5 6 7]


In [20]:
# using step

a=np.arange(10)
b=slice(2,8,2)
print(a[b])

# another method
print()
a1=np.arange(10)
b1=a1[2:8:2]
print(b1)

[2 4 6]

[2 4 6]


In [21]:
# Slicing the arrays

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a)
print()
print (a[1:])
print()
print (a[2:])
print()
print (a[1:2])
print()
print (a[1:2,1:2])

[[1 2 3]
 [3 4 5]
 [4 5 6]]

[[3 4 5]
 [4 5 6]]

[[4 5 6]]

[[3 4 5]]

[[4]]



In [22]:
# Printing nth row using ellipsis (...)

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1,...])                                 # it prints the 1st row

[3 4 5]


In [23]:
# Printing nth column using ellipsis (...)

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[...,1])                                # it prints the 1st column

[2 4 5]


In [25]:
# Printing from nth row using ellipsis (...)

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1:,...])                              # it removes the 1st row

[[3 4 5]
 [4 5 6]]


In [24]:
# Printing from nth column using ellipsis (...)

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[...,1:])                              # it removes the 1st column

[[2 3]
 [4 5]
 [5 6]]


In [27]:
# Advanced Numpy Indexing

x = np.array([[1,2,3],[4,5,6],[7,8,9]])   
print (x)
print()
y = x[[0,1,2], [0,1,0]]   
print (y)                         # it prints the values of those index ((0,0) = 1, (1,1) = 5, (2,0) = 7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 5 7]


In [28]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

rows = np.array([[0,0],[2,2]])           # it prints a matrix (0 0)   (0,1)  for row and column
cols = np.array([[0,1],[0,1]])           #                    (2,2)   (0,1)

y = x[rows,cols] 
print (y)                                # (0,0)=1, (0,1)=2, (2,0)=7, (2,1)=8

[[0 0]
 [2 2]]


In [34]:
x=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14]])
y=x[:3,1:4]
print(y)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# Slicing using advanced index column

x=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14]])

y=x[0:3,[2,3]]                  # [2,3] indicates the index value in array
print(y)

In [35]:
# Boolean Indexing

x=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14]])
y=[x>6]
print(y)

[array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])]


In [36]:
x=np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14]])
print(x[x>6])     # it prints those values alone

[ 7  8  7  8  9 10 11 10 11 12 13 14]


In [3]:
# Not a Number NaN

a = np.array([[np.nan,2,3],[3,np.nan,5],[4,5,6]]) 
print(a)

print()
# Printing NaN from the given array

a = np.array([[np.nan,2,3],[3,np.nan,5],[4,5,6]]) 
print(a[np.isnan(a)])

print()
# Printing all the items in the array except NaN

a = np.array([[np.nan,2,3],[3,np.nan,5],[4,5,6]]) 
print(a[~np.isnan(a)])

[[nan  2.  3.]
 [ 3. nan  5.]
 [ 4.  5.  6.]]

[nan nan]

[2. 3. 3. 5. 4. 5. 6.]


In [4]:
#  Broadcasting  

# Simple Array addition

a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
c=a+b
print(c)

[[5 7 9]]


In [5]:
# Simple Array Multiplication

a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
c=a*b
print(c)

[[ 4 10 18]]


In [6]:
# Two dimensional array - Addition

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4]])
c=a+b
print(c)

[[ 3  5  7]
 [ 6  8 10]]


In [9]:
# Two dimensional array - Multiplication

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4]])
c=a*b
print(c)

print()
a1 = np.array([[1,2,3],[4,5,6]])
b1 = np.array([[2,4,6],[11,10,5]])
c1 = a1*b1
print(c1)

[[ 2  6 12]
 [ 8 15 24]]

[[ 2  8 18]
 [44 50 30]]


In [10]:
# NumPy - Iterating Over Array 

# Simple iteration
a = np.arange(1,10)
for x in a:
    print(x)

1
2
3
4
5
6
7
8
9


In [12]:
# array iteration using 2d array

a = np.arange(1,10)
b = a.reshape(3,3)
print(b)
print()
for x in np.nditer(b):
    print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
2
3
4
5
6
7
8
9


In [14]:
# Transpose of the simple array

a = np.arange(1,13)
b = a.reshape(3,4)
print(b)
print()
b1 = b.T
print(b1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [15]:
# Iterationg the transpose of the above array

a = np.arange(1,13)
b = a.reshape(3,4)
print("The Original Array: ")
print(b)

print()
print("The Transposed Array")
b1 = b.T
print(b1)

print()
for x in np.nditer(b1):
    print(x)

The Original Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

The Transposed Array
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

1
2
3
4
5
6
7
8
9
10
11
12


In [21]:
# Iteration Order -  C-Style

a = np.arange(1,13)
b = a.reshape(3,4)
print("The Original Array")
print(b)
print()
b1 = b.T
print("The Transposed Array")
print(b1)
print()

c = b1.copy(order = 'C')                 # If the same elements are stored using C-style order, 
print("Copied Array")                    # the iterator chooses the more efficient way of iterating over an array.
print()                                       

for x in np.nditer(c):
    print(x)

The Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

The Transposed Array
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Copied Array

1
5
9
2
6
10
3
7
11
4
8
12


In [22]:
# Iteration Order -  F-Style

c = b1.copy(order = 'F')                 # F-style order, is reverse of C style (default/normal method)
print("Copied Array")                   
print()                                       

for x in np.nditer(c):
    print(x)

Copied Array

1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
# Specific Order

# It is possible to force nditer object to use a specific order by explicitly mentioning it.
a = np.arange(1,13)
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Transpose of the above array ")
b=a.T
print(b)

for x in np.nditer(b, order='C'):
    print (x)

Original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose of the above array 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
1
5
9
2
6
10
3
7
11
4
8
12


In [24]:
# Modifying Array Values using op_flags

a = np.arange(1,13)
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Modified array ")

for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=x*2
print (a)

Original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Modified array 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [25]:
a = np.arange(1,13, dtype = 'float32')
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Modified array ")

for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=(x*25)/100
print (a)

Original array is:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Modified array 
[[0.25 0.5  0.75 1.  ]
 [1.25 1.5  1.75 2.  ]
 [2.25 2.5  2.75 3.  ]]


In [26]:
# nditer - external loop

a = np.arange(1,13, dtype="float32")
a = a.reshape(3,4)
print ("Original array is:")
print(a)
print ("Modified array ")

for x in np.nditer(a, flags=['external_loop'], order='F'):
    print (x)
    
# Note: One-dimensional arrays corresponding to each column is traversed by the iterator.

Original array is:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Modified array 
[1. 5. 9.]
[ 2.  6. 10.]
[ 3.  7. 11.]
[ 4.  8. 12.]


In [27]:
# Broadcasting Iteration

a = np.arange(1,13)
a = a.reshape(3,4)
print ("Array 1")
print(a)
print ("Array 2 ")
b = [1,2,3,4]
print(b)
print ("Modified Array ")
for x,y in np.nditer([a,b]):
    print (x,y)

Array 1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 2 
[1, 2, 3, 4]
Modified Array 
1 1
2 2
3 3
4 4
5 1
6 2
7 3
8 4
9 1
10 2
11 3
12 4


In [28]:
# ndarray.reshape - Gives a new shape to an array without changing its data

a=np.array([[1,2,3],[4,5,6]])    # 2rows 3 columns resize to 3 rows 2 column
b=a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
# ndarray.flat - This function returns a 1-D iterator over the array

a=np.array([[101,202,303],[404,505,606]])   
print(a.flat[2])                                      # o/p gives the value of given index 2

303


In [35]:
# ndarray.flatten - it returns a copy of an array collapsed into one dimension. (order of i/p changes in o/p)

a=np.array([[1,2,3],[4,5,6]])   
print(a.flatten())              # default order is C-syle ordering

print()
print(a.flatten(order='F'))     # Specifying F-Style order 

[1 2 3 4 5 6]

[1 4 2 5 3 6]


In [36]:
# ndarray.ravel - This function returns a flattened one-dimensional array. The returned array will have the
#                 same type as that of the input array. The function takes one parameter.

a=np.array([[1,2,3],[4,5,6]])   

print(a.ravel())

[1 2 3 4 5 6]


In [37]:
# numpy.transpose - This function permutes the dimension of the given array.

a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print (a)

b=np.transpose(a)
print (b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [38]:
# numpy.ndarray.T - similar to the numpy.transpose

a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print (a)

b=a.T
print (b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [43]:
# numpy.rollaxis - This function rolls the specified axis backwards, until it lies in a specified position.

a = np.arange(8).reshape(2,2,2) 
print (a)
print("")
print (np.rollaxis(a,2))  

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [44]:
# numpy.swapaxes - This function interchanges the two axes of an array. 

a = np.arange(8).reshape(2,2,2) 
print (a)
print("")
# now swap numbers between axis 0 (along depth) and axis 2 (along width)
print (np.swapaxes(a,2,0))  

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [45]:
# numpy.swapaxes - This function interchanges the two axes of an array. 

a = np.arange(8).reshape(2,2,2) 
print (a)
print("")
# now swap numbers between axis 1 (along depth) and axis 0 (along width)
print (np.swapaxes(a,0,1))  

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


In [5]:
# numpy.expand_dims - This function expands the array by inserting a new axis at the specified position.
# Example - Three Dimensional array

a = np.arange(12).reshape(4,3) 
print("Array a")
print (a)
print("")

b=np.expand_dims(a, axis=1)          # Try changing the axis to  axis=1, axis=3 etc to see difference
print("Array b")
print(b)
print (a.shape)
print (b.shape)

Array a
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Array b
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]
(4, 3)
(4, 1, 3)


In [8]:
# numpy.expand_dims - This function expands the array by inserting a new axis at the specified position.
# Example - Three Dimensional array

a = np.arange(12).reshape(3,2,2) 
print("Array a")
print (a)
print("")

b=np.expand_dims(a, axis=2)             # we can try for all axis = 0,1,2,3,4,...
print("Array b")
print(b)
print (a.shape)
print (b.shape)

Array a
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

Array b
[[[[ 0  1]]

  [[ 2  3]]]


 [[[ 4  5]]

  [[ 6  7]]]


 [[[ 8  9]]

  [[10 11]]]]
(3, 2, 2)
(3, 2, 1, 2)


In [9]:
# numpy.squeeze - This function removes one-dimensional entry from the shape of the given array. 

a = np.arange(8).reshape(1,2,4) 
print ('The original array:') 
print (a)
print("\n")

print ('After applying the squeeze function:') 
b=np.squeeze(a)
print(b)

The original array:
[[[0 1 2 3]
  [4 5 6 7]]]


After applying the squeeze function:
[[0 1 2 3]
 [4 5 6 7]]


In [10]:
# np.broadcast_to - This function broadcasts an array to a new shape.

import numpy as np 
a = np.arange(4).reshape(1,4) 

print ('The original array:') 
print (a )
print ('\n' ) 

print ('After broadcasted:') 
print (np.broadcast_to(a,(4,4)))

The original array:
[[0 1 2 3]]


After broadcasted:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [12]:
# numpy.append - This function adds values at the end of an input array.

a=np.arange(12).reshape(3,4)
print(a)
print() 
b=np.append(a,[[11,22,33]])   
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 11 22 33]


In [13]:
# numpy.append -Setting axis

a=np.arange(12).reshape(3,4)
print(a)
print() 
b=np.append(a,[[11,22,33,44]],axis=0)   
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [11 22 33 44]]


In [14]:
# numpy.insert - This function inserts values in the input array along the given axis and before the given index.

a=np.arange(12).reshape(3,4)
print(a)
print() 
b=np.insert(a,4, [11,22,33,44])   # Inserting new rows
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0  1  2  3 11 22 33 44  4  5  6  7  8  9 10 11]


In [18]:
# numpy.insert - Using axis

a=np.arange(12).reshape(3,4)
print(a)
print() 
b=np.insert(a,1, [11,22,33,44], axis = 0)   # Inserting new rows
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [11 22 33 44]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
a=np.arange(12).reshape(3,4)
print(a)
print() 
b=np.insert(a,1, [11,22,34], axis = 1)   # Inserting new rows
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0 11  1  2  3]
 [ 4 22  5  6  7]
 [ 8 34  9 10 11]]


In [22]:
# numpy.delete - This function returns a new array with the specified subarray deleted from the input array.

a=np.arange(12).reshape(3,4)
print(a)
print() 
b=np.delete(a, 1)   # Delete a value
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0  2  3  4  5  6  7  8  9 10 11]


In [23]:
# numpy.delete - Using axis

a=np.arange(12).reshape(3,4)
print(a)
print() 
b=np.delete(a, 1, axis= 1 )   # Deleting a column using row
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [24]:
# numpy.unique - This function returns an array of unique elements in the input array.

a=np.array([[1,2,1],[3,1,3],[1,1,2]])
print(a)
print('\n')

b=np.unique(a)         # Unique elements in the array
print(b)

[[1 2 1]
 [3 1 3]
 [1 1 2]]


[1 2 3]


In [25]:
a=np.array([[1,2,1],[3,1,3],[1,1,2]])
print(a)
print()

b=np.unique(a)          # Unique elements in the array
print(b)

b,indices=np.unique(a,return_index='true')
print("\nPrintng Indices")
print (indices)

[[1 2 1]
 [3 1 3]
 [1 1 2]]

[1 2 3]

Printng Indices
[0 1 3]


In [26]:
#  NumPy - Binary Operators 

# Printing Binary Numbers

a=27
print (bin(a))

0b11011


In [27]:
# Bitwise AND Operator 
# Using function - bitwise_and

print (np.bitwise_and(22,26))
print()

# Bitwise OR Operator 
# Using function - bitwise_or

print (np.bitwise_or(22,26))
print()

# Bitwise NOT Operator 
# Using function - invert

print (np.invert([13]))

18

30

[-14]


In [28]:
#  String Functions 

# String Concatenation
print (np.char.add('Hello','World'))
print()
print (np.char.add(['Hello','World'],['Super','Star']))

HelloWorld

['HelloSuper' 'WorldStar']


In [29]:
# String Multiply
print (np.char.multiply('Hello', 3))

HelloHelloHello


In [30]:
# np.char.center
# Returns a copy of the given string with elements centered in a string of specified length

print (np.char.center('Hello', 20, fillchar='#'))

#######Hello########


In [32]:
# numpy.char.capitalize()
# Returns a copy of the string with only the first character capitalized

print (np.char.capitalize('hello world'))
print()

# numpy.char.title()
# Returns the element-wise title cased version of the string or unicode

print (np.char.title('hello world'))

Hello world

Hello World


In [33]:
# numpy.char.lower()
# Returns an array with the elements converted to lowercase
   
print (np.char.lower('HELLO WORLD'))
print()

# numpy.char.upper()
# Returns an array with the elements converted to uppercase

print (np.char.upper('hello world'))

hello world

HELLO WORLD


In [34]:
# numpy.char.split()
# Returns a list of the words in the string, using separatordelimiter

print (np.char.split('hello how are you'))
print()

print (np.char.split('hello, how, are, you'),sep=',')  

['hello', 'how', 'are', 'you']

['hello,', 'how,', 'are,', 'you']


In [35]:
# numpy.char.splitlines()
# Returns a list of the lines in the element, breaking at the line boundaries

print (np.char.splitlines('hello\n how are you'))

['hello', ' how are you']


In [36]:
# numpy.char.strip()
# Returns a copy with the leading and trailing characters removed

print (np.char.strip('hello how are you', 'h'))      # removes 'h' at starting and ending
print (np.char.strip('hello how are you ah', 'h'))

ello how are you
ello how are you a


In [37]:
# numpy.char.join()
# Returns a string which is the concatenation of the strings in the sequence

print (np.char.join('-','hello world'))
print()
print (np.char.join(['-','+'],['hello', 'world']))

h-e-l-l-o- -w-o-r-l-d

['h-e-l-l-o' 'w+o+r+l+d']


In [38]:
# numpy.char.replace()
# Returns a copy of the string with all occurrences of substring replaced by the new string

print (np.char.replace('hello hai how is He', 'h','e'))

eello eai eow is He


In [40]:
# numpy.char.encode()
# Calls str.encode element-wise

a= np.char.encode('hello world','cp500')
print (a)

# numpy.char.decode()
# Calls str.decode element-wise
print()
print (np.char.decode(a,'cp500'))

b'\x88\x85\x93\x93\x96@\xa6\x96\x99\x93\x84'

hello world


In [41]:
#  Mathematical Functions 

# Finding Sine Values

print (np.sin(0))

# Finding Cosine Values
print()
print (np.cos(0))

# Finding Tangent Values
print()
print (np.tan(0))

0.0

1.0

0.0


In [42]:
# Finding Sine Values for 30

print (np.sin(30*np.pi/180))

# Finding Cosine Values for 30

print()
print (np.cos(30*np.pi/180))

0.49999999999999994

0.8660254037844387


In [43]:
#  numpy.ptp() function returns the range (maximum-minimum) of values along an axis.

a=np.array([1,2,3])  # 3-1 = 2
print(np.ptp(a))

2


In [44]:
# Percentile (or a centile) is a measure used in statistics indicating the value below which a given percentage 
#   of observations in a group of observations fall.

a=np.array([1,2,3])
print(np.percentile(a,10))

1.2


In [45]:
# Median is defined as the value separating the higher half of a data sample from the lower half.

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.median(a))

50.0


In [46]:
# The numpy.mean() function returns the arithmetic mean of elements in the array.

a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.mean(a))

50.0


In [47]:
# Standard deviation is the square root of the average of squared deviations from mean.

a=np.array([10,20,30])
print(np.std(a))

8.16496580927726


In [48]:
# Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2). 

a=np.array([10,20,30])
print(np.var(a))

66.66666666666667
